eregister/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('pages.urls')),
    # path('events/api/', include('events.urls')),
    path('admin/', admin.site.urls),
]

pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('profile/<int:user_id>/', views.profile, name='profile'),
    path('password/change/', views.change_password, name='password_change'),
    path('password/reset/<int:user_id>/', views.reset_password, name='password_reset'),
    path('password/set/', views.set_default_password, name='password_set_default'),
    path('organizer/manage/', views.organizer_manage, name='organizer_manage'),
    path('participant/manage/', views.participant_manage, name='participant_manage'),
    path('organizer/register/', views.register_organizer, name='register_organizer'),
    path('participant/register/', views.register_participant, name='register_participant'),
    path('user/edit/<int:user_id>/', views.user_edit, name='user_edit'),
    path('participant/edit/<int:user_id>/', views.participant_user_edit, name='participant_user_edit'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('events/', views.event_home, name='event_home'),
    path('event/details/<int:event_id>/', views.event_details, name='event_details'),
    path('event/manage/', views.event_manage, name='event_manage'),
    path('event/create/', views.event_create, name='event_create'),
    path('event/edit/<int:event_id>/', views.event_edit, name='event_edit'),
    path('event/participate/<int:event_id>/', views.event_participate, name='event_participate'),
    path('exportcsv/<int:event_id>/', views.generate_csv, name='generate_csv'),
    path('sendsurvey/<int:event_id>/', views.send_survey, name='send_survey'),
]

users/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_("email address"), unique=True)
    first_name = models.CharField(max_length=50, blank=True)
    middle_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)
    user_id = models.CharField(max_length=50, blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class ParticipantUser(models.Model):
    email = models.EmailField(_("email address"), unique=True)
    first_name = models.CharField(max_length=50, blank=True)
    middle_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)
    user_id = models.CharField(max_length=50, blank=True)
    date_joined = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.email

users/views.py
from django.shortcuts import render

# Create your views here.

pages/templates/pages/user/edit_participant.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="edit_user_form_con">
    <form method="post" class="v_form" action="{% url 'participant_user_edit' user_id=user_id %}">
        {% csrf_token %}
        {{ user_form }}
        <div class="v_form_footer">
            <button type="submit">Submit</button>
        </div>
    </form>
</div>
{% endblock content %}

pages/templates/pages/user/edit_user.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="edit_user_form_con">
    <form method="post" class="v_form" action="{% url 'user_edit' user_id=user_id %}">
        {% csrf_token %}
        {{ user_form }}
        <div class="v_form_footer">
            <button type="submit">Submit</button>
        </div>
    </form>
</div>
{% endblock content %}

pages/templates/pages/user/manage_organizer.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>Manage Organizers</h1>
<div class="btns">
    <a href="{% url 'register_organizer' %}" class="btn"><i class="fa-solid fa-cash-register"></i> Register Organizer</a>
    <a id="set_default" href="#!" class="btn btn-secondary"><i class="fa-solid fa-key"></i> Set Default Password</a>
    <a id="trigger" href="javascript:;" class="btn btn-danger"><i class="fa-solid fa-trash"></i> Delete</a>
</div>
<div class="search">
    <form method="GET">
        <input type="text" name="s" placeholder="Search User ID" />
        <button type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
    </form>
</div>
<table class="users-tbl">
    <thead>
    <tr>
        <th></th>
        <th>User ID</th>
        <th>Email</th>
        <th>Last Name</th>
        <th>First Name</th>
        <th>Middle Name</th>
        <th>Administrator</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
{% for user in users %}
    <tr>
        <td><input name="users_checkbox" type="checkbox" value="{{ user.pk }}" /></td>
        <td>{{ user.user_id }}</td>
        <td>{{ user.email }}</td>
        <td>{{ user.last_name }}</td>
        <td>{{ user.first_name }}</td>
        <td>{{ user.middle_name }}</td>
        <td>{{ user.is_superuser }}</td>
        <td><a href="{% url 'user_edit' user_id=user.id %}"><i class="fa-solid fa-pencil"></i> Edit</a></td>
    </tr>
    </tbody>
{% endfor %}
</table>

{% if users.has_other_pages %}
    <div class="pagination">
        <span class="step-links">
            {% if users.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ users.previous_page_number }}">previous</a>
            {% endif %}

            {% for page_num in users.paginator.page_range %}
                {% if users.number == page_num %}
                    <span class="current-page">{{ page_num }}</span>
                {% else %}
                    <a href="?page={{ page_num }}">{{ page_num }}</a>
                {% endif %}
            {% endfor %}

            {% if users.has_next %}
                <a href="?page={{ users.next_page_number }}">next</a>
                <a href="?page={{ users.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endif %}

<!--SET DEFAULT PASSWORD MODAL-->
<!--<div id="modal_alert" style="display:none;">-->
<!--    <div id="modal_overlay"></div>-->
<!--    <div id="modal">-->
<!--        <div class="modal_con">-->
<!--            <div class="modal_header">-->
<!--                <h2 id="modal_title">header</h2>-->
<!--            </div>-->
<!--            <div class="modal_body">-->
<!--                <p id="modal_text">body</p>-->
<!--            </div>-->
<!--            <div id="modal_footer" class="modal_footer">-->
<!--                <button id="modal_yes">Yes</button>-->
<!--                <button id="modal_no">No</button>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->

{% endblock content %}

{% block scripts %}
<script>
var values = [];

function csrfSafeMethod(method) {
      // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
$.ajaxSetup({
      beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", '{{csrf_token}}');
        }
      }
});

<!--ON DELETE-->
$("#trigger").on("click", function(){
    var content = {
        'title': 'Delete Users?',
        'body': 'Are you sure you want to delete the selected users?, you won\'t be able to revert this.',
        'onYes': function(){
            $.each($("input[name='users_checkbox']:checked"), function(){
              values.push($(this).val());
            });
            $.ajax({
             type: 'POST',
             contentType: 'application/json; charset=utf-8',
             data: JSON.stringify({"delete_list": values}),
             dataType: 'json',
                 success: function(response){
                     if(response["isSuccess"]){
                            window.location.href = "{% url 'organizer_manage' %}";
                     }
                     else{
                         alert("error");
                     }
                 },
                 error: function(response){
                     alert("error");
                 }
            });
        }
    }
    showModal(content);

});


</script>
{% endblock scripts %}

pages/templates/pages/user/manage_participant.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>Manage Participants</h1>
<div class="btns">
    <a href="{% url 'register_participant' %}" class="btn"><i class="fa-solid fa-cash-register"></i> Register Participant</a>
    <a id="trigger" href="javascript:;" class="btn btn-danger"><i class="fa-solid fa-trash"></i> Delete</a>
</div>
<div class="search">
    <form method="GET">
        <input type="text" name="s" placeholder="Search Participant ID" />
        <button type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
    </form>
</div>
<table class="users-tbl">
    <thead>
    <tr>
        <th></th>
        <th>User ID</th>
        <th>Email</th>
        <th>Last Name</th>
        <th>First Name</th>
        <th>Middle Name</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
{% for participant_user in participant_users %}
    <tr>
        <td><input name="users_checkbox" type="checkbox" value="{{ participant_user.pk }}" /></td>
        <td>{{ participant_user.user_id }}</td>
        <td>{{ participant_user.email }}</td>
        <td>{{ participant_user.last_name }}</td>
        <td>{{ participant_user.first_name }}</td>
        <td>{{ participant_user.middle_name }}</td>
        <td><a href="{% url 'participant_user_edit' user_id=participant_user.id %}"><i class="fa-solid fa-pencil"></i> Edit</a></td>
    </tr>
    </tbody>
{% endfor %}
</table>

{% if participant_users.has_other_pages %}
    <div class="pagination">
        <span class="step-links">
            {% if participant_users.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ participant_users.previous_page_number }}">previous</a>
            {% endif %}

            {% for page_num in participant_users.paginator.page_range %}
                {% if participant_users.number == page_num %}
                    <span class="current-page">{{ page_num }}</span>
                {% else %}
                    <a href="?page={{ page_num }}">{{ page_num }}</a>
                {% endif %}
            {% endfor %}

            {% if participant_users.has_next %}
                <a href="?page={{ participant_users.next_page_number }}">next</a>
                <a href="?page={{ participant_users.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endif %}

{% endblock content %}

{% block scripts %}
<script>
    var values = [];

    function csrfSafeMethod(method) {
          // these HTTP methods do not require CSRF protection
          return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
    $.ajaxSetup({
          beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
              xhr.setRequestHeader("X-CSRFToken", '{{csrf_token}}');
            }
          }
    });

    <!--ON DELETE-->
    $("#trigger").on("click", function(){
        var content = {
            'title': 'Delete Users?',
            'body': 'Are you sure you want to delete the selected users?, you won\'t be able to revert this.',
            'onYes': function(){
                $.each($("input[name='users_checkbox']:checked"), function(){
                  values.push($(this).val());
                });
                $.ajax({
                 type: 'POST',
                 contentType: 'application/json; charset=utf-8',
                 data: JSON.stringify({"delete_list": values}),
                 dataType: 'json',
                     success: function(response){
                         if(response["isSuccess"]){
                                window.location.href = "{% url 'participant_manage' %}";
                         }
                         else{
                             alert("error");
                         }
                     },
                     error: function(response){
                         alert("error");
                     }
                });
            }
        }
        showModal(content);

    })
</script>

{% endblock scripts %}

pages/templates/pages/user/manage_user.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>Manage Users</h1>
<div class="links">
    <a href="{% url 'register_user' %}">Register User</a>
    <a id="trigger" href="javascript:;">Delete</a>
</div>
<div class="search">
    <form method="GET">
        <input type="text" name="s" placeholder="Search User ID" />
        <button type="submit">Search</button>
    </form>
</div>
<table class="users-tbl">
    <thead>
    <tr>
        <th></th>
        <th>User ID</th>
        <th>Email</th>
        <th>Last Name</th>
        <th>First Name</th>
        <th>Middle Name</th>
        <th>Administrator</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
{% for user in users %}
    <tr>
        <td><input name="users_checkbox" type="checkbox" value="{{ user.pk }}" /></td>
        <td>{{ user.user_id }}</td>
        <td>{{ user.email }}</td>
        <td>{{ user.last_name }}</td>
        <td>{{ user.first_name }}</td>
        <td>{{ user.middle_name }}</td>
        <td>{{ user.is_superuser }}</td>
        <td><a href="{% url 'user_edit' user_id=user.id %}">Edit</a></td>
    </tr>
    </tbody>
{% endfor %}
</table>

{% if users.has_other_pages %}
    <div class="pagination">
        <span class="step-links">
            {% if users.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ users.previous_page_number }}">previous</a>
            {% endif %}

            {% for page_num in users.paginator.page_range %}
                {% if users.number == page_num %}
                    <span class="current-page">{{ page_num }}</span>
                {% else %}
                    <a href="?page={{ page_num }}">{{ page_num }}</a>
                {% endif %}
            {% endfor %}

            {% if users.has_next %}
                <a href="?page={{ users.next_page_number }}">next</a>
                <a href="?page={{ users.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endif %}

{% endblock content %}

{% block scripts %}
<script>
var values = [];

function csrfSafeMethod(method) {
      // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
$.ajaxSetup({
      beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", '{{csrf_token}}');
        }
      }
});

<!--ON DELETE-->
$("#trigger").on("click", function(){
    var content = {
        'title': 'Delete Users?',
        'body': 'Are you sure you want to delete the selected users?, you won\'t be able to revert this.',
        'onYes': function(){
            $.each($("input[name='users_checkbox']:checked"), function(){
              values.push($(this).val());
            });
            $.ajax({
             type: 'POST',
             contentType: 'application/json; charset=utf-8',
             data: JSON.stringify({"delete_list": values}),
             dataType: 'json',
                 success: function(response){
                     if(response["isSuccess"]){
                            window.location.href = "{% url 'user_manage' %}";
                     }
                     else{
                         alert("error");
                     }
                 },
                 error: function(response){
                     alert("error");
                 }
            });
        }
    }
    showModal(content);

})
</script>
{% endblock scripts %}

pages/templates/pages/user/profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="profile_con">
  <h2>Profile</h2>
  <p>
    <span>User ID: </span> {{ user.user_id }}
  </p>
  <p>
    <span>Email: </span> {{ user.email }}
  </p>
  <p>
    <span>First Name: </span> {{ user.first_name }}
  </p>
  <p>
    <span>Middle Name: </span> {{ user.middle_name }}
  </p>
  <p>
    <span>Last Name: </span> {{ user.last_name }}
  </p>

  {% if request.user == user %}
  <div class="profile_functions">
    <ul>
      <li><a href="#!">Edit Profile</a></li>
      <li><a id="change_password" href="#!">Change Password</a></li>
      <li><a href="{% url 'password_reset' user_id=user.pk %}">Reset Password</a></li>
    </ul>
  </div>
  {% endif %}
</div>
{% endblock content %}

{% block scripts %}
<script>
    $('#change_password').on("click", function(){
        var content = {
            'title': 'Change Password',
            'body': '{{ change_password_form }}',
            'showFooter': false,
            'outsideClick': true,
            'showFooter': true,
            'onYes': function(){
              alert('test');
            }
        }
        showModal(content);
    });
</script>
{% endblock scripts %}

pages/templates/pages/user/register_organizer.html
{% extends "base.html" %}
{% load static %}

{% block head %}
    <style>
        #close_scanner{
            border: none;
            background: var(--color-secondary);
            color: #ffff;
            padding: 10px 25px;
            font-size: 18px;
            margin-top: 15px;
            cursor: pointer;
            transition: .6s;
        }
        #close_scanner:hover{
            background: var(--color-primary);
            box-shadow: 0 0 0 1px var(--color-secondary);
            color: var(--color-secondary);
        }
        #scan_qr {
          color: #fff;
          display: inline-block;
          padding: 0 15px;
          font-weight: 700;
          font-size: 19px;
        }

        #scan_qr:hover {
          text-decoration: none;
        }
    </style>
{% endblock %}

{% block content %}
<div class="register_form_con">
    <form id="register_form" class="v_form" method="post">
        <h2>Register Organizer</h2>

        {% csrf_token %}
        {{ register_user_form }}
        <div class="v_form_footer">
            <a href="#!" id="scan_qr">Scan QR</a>
            <button type="submit">Submit</button>
        </div>
    </form>
</div>
{% endblock content %}

{% block scripts %}
<script src="{% static 'assets/instascan.min.js' %}"></script>
<script type="text/javascript">

    $("#scan_qr").on("click", function(){
        var content = {
            'title': 'Scan QR',
            'body': '<video id="preview" style="width: 448px; height: 336px;"></video><button type="button" id="close_scanner">Close</button>',
            'showFooter': false,
            'outsideClick': false,
        }
        showModal(content);

        var scanner = new Instascan.Scanner({ video: document.getElementById('preview'), scanPeriod: 5, mirror: false });
        scanner.addListener('scan',function(content){
            $("#id_user_id").val(content);
            hideModal();
            scanner.stop();
        });
        Instascan.Camera.getCameras().then(function (cameras){
            if(cameras.length>0){
                scanner.start(cameras[0]);
                $('[name="options"]').on('change',function(){

                    if(cameras[1]!=""){
                        scanner.start(cameras[1]);
                    }else{
                        alert('No Back camera found!');
                    }

                });
            }else{
                console.error('No cameras found.');
                alert('No cameras found.');
            }
        }).catch(function(e){
            console.error(e);
            alert(e);
        });

        $("#close_scanner").on("click", function(){
            hideModal();
            scanner.stop();
        });
    });

</script>
{% endblock scripts %}

pages/templates/pages/user/register_participant.html
{% extends "base.html" %}
{% load static %}

{% block head %}
    <style>
        #close_scanner{
            border: none;
            background: var(--color-secondary);
            color: #ffff;
            padding: 10px 25px;
            font-size: 18px;
            margin-top: 15px;
            cursor: pointer;
            transition: .6s;
        }
        #close_scanner:hover{
            background: var(--color-primary);
            box-shadow: 0 0 0 1px var(--color-secondary);
            color: var(--color-secondary);
        }
        #scan_qr {
          color: #fff;
          display: inline-block;
          padding: 0 15px;
          font-weight: 700;
          font-size: 19px;
        }

        #scan_qr:hover {
          text-decoration: none;
        }
    </style>
{% endblock %}

{% block content %}
<div class="register_form_con">
    <form id="register_form" class="v_form" method="post">
        <h2>Register Participant</h2>

        {% csrf_token %}
        {{ register_participant_form }}
        <div class="v_form_footer">
            <a href="#!" id="scan_qr">Scan QR</a>
            <button type="submit">Submit</button>
        </div>
    </form>


</div>
{% endblock content %}

{% block scripts %}
<script src="{% static 'assets/instascan.min.js' %}"></script>
<script type="text/javascript">

    $("#scan_qr").on("click", function(){
        var content = {
            'title': 'Scan QR',
            'body': '<video id="preview" style="width: 448px; height: 336px;"></video><button type="button" id="close_scanner">Close</button>',
            'showFooter': false,
            'outsideClick': false,
        }
        showModal(content);

        var scanner = new Instascan.Scanner({ video: document.getElementById('preview'), scanPeriod: 5, mirror: false });
        scanner.addListener('scan',function(content){
            $("#id_user_id").val(content);
            hideModal();
            scanner.stop();
        });
        Instascan.Camera.getCameras().then(function (cameras){
            if(cameras.length>0){
                scanner.start(cameras[0]);
                $('[name="options"]').on('change',function(){

                    if(cameras[1]!=""){
                        scanner.start(cameras[1]);
                    }else{
                        alert('No Back camera found!');
                    }

                });
            }else{
                console.error('No cameras found.');
                alert('No cameras found.');
            }
        }).catch(function(e){
            console.error(e);
            alert(e);
        });

        $("#close_scanner").on("click", function(){
            hideModal();
            scanner.stop();
        });
    });



</script>
{% endblock scripts %}

pages/templates/pages/user/register_user.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="register_form_con">
    <form id="register_form" class="v_form" method="post">
        <h2>Register</h2>

        {% csrf_token %}
        {{ register_user_form }}
        <div class="v_form_footer">
            <button type="submit">Submit</button>
        </div>
    </form>
</div>
{% endblock content %}